services:
  bunbackend:
    image: bunbackend
    build:
      context: web-version-V2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
